name = "space_the_last_place_to_work"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.37"
gleam_erlang = "~> 0.29"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
